CREATE DATABASE Trazabilidad_SGVA;
USE Trazabilidad_SGVA;

CREATE TABLE trazabilidad(
id_trazabilidad INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre_empresa VARCHAR(100) NOT NULL, 
Nombre_RH VARCHAR(45),
fecha_inicio VARCHAR(45), 
fecha_fin VARCHAR(45),
fecha_cierre VARCHAR(45), 
Direccion VARCHAR (150),
Numero VARCHAR(45),     
estado VARCHAR (45)
);

CREATE TABLE Empresa(
id_empresa INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
codigo_empresa VARCHAR(80) NOT NULL,
nombre_empresa VARCHAR(150) NOT NULL
);

DESCRIBE Empresa;

INSERT INTO Empresa (codigo_empresa, nombre_empresa) VALUES 
('COD1', 'VOSOFTSAS'),
('COD2', 'INFORMATION WORKERS SAS'),
('COD3', 'GENSER POWER COLOMBIA'),
('COD4', 'VASS CONSULTORIA DE SISTEMAS COLOMBIA SAS'),
('COD5', 'CONTINENTAL ASSIST COLOMBIASAS'),
('COD6', 'ENFRAGEN COLOMBIA SAS'),
('COD7', 'HOSOCIAL SAS'),
('COD8', 'NTT DATA CEILOMBIASAS'),
('COD9', 'JAZZPLAT COLOMBIASAS'),
('COD10', 'UNIVERSIDAD ANTONIO NARIÑO'),
('COD11', 'TECPETROL COLOMBIA SAS'),
('COD12', 'ADO TECHNOLOGIES COLOMBIA SAS'),
('COD13', 'INDUSTRIA MILITAR'),
('COD14', 'COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENESTAR SOCIAL BENEFICIAR'),
('COD15', 'IDENTIDAD TELECOM SAS'),
('COD16', 'SOPORTE Y LOGISTICASAS'),
('COD17', 'WORLD VISION INTERNATIONAL'),
('COD18', 'SQDM SAS'),
('COD19', 'INSTALEAPS AS'),
('COD20', 'HIKVISION COLOMBIA\'S AS');

ALTER TABLE Empresa
DROP COLUMN id_empresa;

ALTER TABLE Empresa
ADD PRIMARY KEY(codigo_empresa);

DESCRIBE Empresa;

ALTER TABLE trazabilidad
CHANGE nombre_empresa COD_EMPRESA VARCHAR (100) NOT NULL;